<?php

use App\customer;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SurveySeeder extends Seeder
{
    public function run()
    {

        $data = [
            [
                'id' => 64,
                'area' => 'Yogyakarta',
                'name' => 'wahyudi',
                'rayon' => 'Bantul',
                'kab' => 'bantul kota',
                'IG' => null,
                'email' => null,
                'venue' => 'PUSAT PEMBELANJAAN',
                'umur' => '41-50thn',
                'id_user' => 15,
                'created_at' => '2023-04-10 07:05:55',
                'updated_at' => '2023-04-27 13:18:54',
                'rasadip' => 'Enak',
                'telp' => '90124810461',
                'jenis_kelamin' => 'laki-laki',
                'pekerjaan' => 'Karyawan',
                'rokok' => 'Diplomat Mild Menthol',
                'jml_beli' => 1,
                'pernahrasa' => 'Diplomat Mild Menthol',
                'kemasan' => 'Menarik',
                'open' => 1,
                'hargadip' => 1,
                'akanbeli' => 1,
                'alasan' => 'Rasa Enak',
                'tempatbeli' => 'warung',
            ],
            [
                'id' => 75,
                'area' => 'Solo',
                'name' => 'agus',
                'rayon' => 'Solo',
                'kab' => 'banjarsari',
                'IG' => null,
                'email' => null,
                'venue' => 'C&B',
                'umur' => '18-25thn',
                'id_user' => 9,
                'created_at' => '2023-04-11 13:13:07',
                'updated_at' => '2023-04-11 13:13:07',
                'rasadip' => 'Enak',
                'telp' => '085396298393',
                'jenis_kelamin' => 'laki-laki',
                'pekerjaan' => 'Karyawan',
                'rokok' => 'LA Light',
                'jml_beli' => 1,
                'pernahrasa' => 'Diplomat Mild',
                'kemasan' => 'Menarik',
                'open' => 1,
                'hargadip' => 1,
                'akanbeli' => 1,
                'alasan' => 'Rasa Enak',
                'tempatbeli' => 'warung',
            ],
            [
                'id' => 84,
                'area' => 'Semarang',
                'name' => 'Denny',
                'rayon' => 'Salatiga',
                'kab' => 'Tingkir',
                'IG' => null,
                'email' => null,
                'venue' => 'SC',
                'umur' => '26-30thn',
                'id_user' => 13,
                'created_at' => '2023-04-13 12:47:52',
                'updated_at' => '2023-04-13 12:47:52',
                'rasadip' => 'Enak',
                'telp' => '087717318554',
                'jenis_kelamin' => 'laki-laki',
                'pekerjaan' => 'Karyawan',
                'rokok' => 'Pro Mild',
                'jml_beli' => 1,
                'pernahrasa' => 'Diplomat Mild',
                'kemasan' => 'Menarik',
                'open' => 1,
                'hargadip' => 1,
                'akanbeli' => 1,
                'alasan' => 'Harga Terjangkau',
                'tempatbeli' => 'Indomaret',
            ],
            [
                'id' => 85,
                'area' => 'Yogyakarta',
                'name' => 'Aryog',
                'rayon' => 'Bantul',
                'kab' => 'Bantul',
                'IG' => 'Aryogalihprakoso',
                'email' => null,
                'venue' => 'PA',
                'umur' => '26-30thn',
                'id_user' => 28,
                'created_at' => '2023-04-26 02:34:45',
                'updated_at' => '2023-04-26 02:34:45',
                'rasadip' => 'Enak',
                'telp' => null,
                'jenis_kelamin' => 'laki-laki',
                'pekerjaan' => 'Karyawan',
                'rokok' => 'LA Light',
                'jml_beli' => 1,
                'pernahrasa' => 'Diplomat Mild',
                'kemasan' => 'Menarik',
                'open' => 1,
                'hargadip' => 1,
                'akanbeli' => 1,
                'alasan' => 'Rasa Enak',
                'tempatbeli' => 'Idm',
            ],
            [
                'id' => 86,
                'area' => 'Yogyakarta',
                'name' => 'Indra',
                'rayon' => 'Bantul',
                'kab' => 'Bantul',
                'IG' => null,
                'email' => null,
                'venue' => 'PA',
                'umur' => '18-25thn',
                'id_user' => 25,
                'created_at' => '2023-04-26 02:35:07',
                'updated_at' => '2023-04-26 02:35:07',
                'rasadip' => 'Enak',
                'telp' => '085292064423',
                'jenis_kelamin' => 'laki-laki',
                'pekerjaan' => 'Karyawan',
                'rokok' => 'Pro Mild',
                'jml_beli' => 1,
                'pernahrasa' => 'Diplomat Mild',
                'kemasan' => 'Menarik',
                'open' => 0,
                'hargadip' => 1,
                'akanbeli' => 1,
                'alasan' => 'Rasa Enak',
                'tempatbeli' => 'Warung',
            ],
            [
                'id' => 87,
                'area' => 'Yogyakarta',
                'name' => 'LOGI',
                'rayon' => 'Bantul',
                'kab' => 'Bantul',
                'IG' => null,
                'email' => null,
                'venue' => 'PA',
                'umur' => '26-30thn',
                'id_user' => 27,
                'created_at' => '2023-04-26 02:36:16',
                'updated_at' => '2023-04-26 02:36:16',
                'rasadip' => 'Biasa',
                'telp' => '087845689928',
                'jenis_kelamin' => 'laki-laki',
                'pekerjaan' => 'Wiraswasta',
                'rokok' => 'A Mild',
                'jml_beli' => 1,
                'pernahrasa' => 'Diplomat Mild',
                'kemasan' => 'Menarik',
                'open' => 1,
                'hargadip' => 0,
                'akanbeli' => 0,
                'alasan' => null,
                'tempatbeli' => null,
            ],
        ];

        DB::table('customer')->insert($data);
    }
}